version: '3.8'

services:
  identityserver5:
    container_name: dev-identityserver5
    build:
      context: ..
      dockerfile: IdentityServer/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - kalinus-network
  
  postgresql:
    image: postgres
    container_name: dev-postgre
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=burgut
      - POSTGRES_USER=kalinus
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    networks:
      - kalinus-network
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

networks:
  kalinus-network:
    name: kalinus-network
    driver: bridge
  
volumes:
  db_data:
    driver: local
